### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by Shorla**
Made the new adjustments

### CODE REVIEW

**Comment by annefou** [comment]
That is great. Just for your record: you usually do not need to create a new branch and a new Pull Request every time you adjust and make new changes. You can push to your branch your additional changes and they will be part of the same Pull Request. 

You rchanges are great. I think we are nearly there (probably a few more changes; I need to check more carefully). 

You can add yourself as a contributor. Thanks a lot for your input. Well done.

**Comment by Shorla** [comment]
@annefou Thank you very much for giving me this opportunity. I can't quite figure out how not to create a new branch but I will try out some things. Thanks.

**Comment by annefou** [comment]
> @annefou Thank you very much for giving me this opportunity. I can't quite figure out how not to create a new branch but I will try out some things. Thanks.


You can keep updating the same branch. This Pull Request will be updated automatically with your changes. 
Thanks.

**Comment by franzihe** [comment]
@annefou @Shorla, let me know when you merged to the cmip6 branch, then I can add some more examples?

**Comment by annefou** [comment]
I'll merge it now. thanks.

**Pull request merged**
